[tool.poetry]
name = "brim"
version = "0.0.1"
description = "A Modular and Extensible Open-Source Framework for Creating Bicycle-Rider Models"
authors = ["TJStienstra <T.J.Stienstra@student.tudelft.nl>"]
license = "CC0-1.0"
readme = "README.md"
repository = "https://github.com/TJStienstra/brim"

[tool.poetry.dependencies]
python = "^3.8"
sympy = {git = "https://github.com/TJStienstra/sympy.git", rev = "sympy-for-brim"}
symmeplot = {git = "https://github.com/TJStienstra/symmeplot.git", optional = true}

[tool.poetry.group.lint.dependencies]
ruff = "^0.0.254"

[tool.poetry.group.test.dependencies]
pytest = "^7.2.2"
coverage = {extras = ["toml"], version = "^7.2.1"}
pytest-cov = "^4.0.0"
numpy = "^1.24.2"


[tool.poetry.group.docs.dependencies]
sphinx = "^6.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py38"
line-length = 88
select = ["A", "B", "C", "D", "E", "F", "I", "N", "Q", "W", "NPY", "RUF", "SIM", "TID",
          "T20", "UP"]
ignore = ["A003", "D100", "D104", "D105", "D107", "D203", "D213"]
show-source = true

[tool.ruff.per-file-ignores]
"tests/*" = ["D", "S101"]

[tool.ruff.pydocstyle]
convention = "numpy"

[tool.mypy]
python_version = "3.8"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.coverage.paths]
source = ["src"]

[tool.coverage.run]
branch = true
source = ["brim"]

[tool.coverage.report]
show_missing = true
fail_under = 100
exclude_lines = [
    "pragma: no cover",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
]
omit = [
    "src/brim/utilities/plotting.py",
]
