# Based of: https://github.com/eeholmes/readthedoc-test
on:
  push:
    workflow_run:
      workflows: [tests]
      types: [completed]
      branches: [main]
permissions:
  contents: write

jobs:

  deploy_docs_job:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install pandoc
      - name: Create the tutorials' environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: docs/tutorials/tutorials_environment.yml
          init-shell: >-
            bash
            powershell
          cache-environment: true
          post-cleanup: 'all'
      - name: Deactivate the tutorials environment
        run: micromamba deactivate
      - name: Install poetry
        run: pipx install poetry==1.6.1
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: poetry install --with docs --all-extras
      - name: make the sphinx docs
        run: |
          poetry run make -C docs clean
          poetry run make -C docs html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          force_orphan: true
