# Based of: https://github.com/eeholmes/readthedoc-test
on:
  push:
    workflow_run:
      workflows: [tests]
      types: [completed]
      branches: [main]
permissions:
  contents: write

jobs:

  deploy_docs_job:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry==1.4.0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: poetry install --with docs --extras plotting
      - name: make the sphinx docs
        run: |
          poetry run make -C docs clean
          poetry run make -C docs html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/
          force_orphan: true
