name: Lint

on:
  pull_request:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry==1.4.0
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: poetry install --with lint
      - name: Linting
        run: |
          poetry run ruff . --verbose
          poetry run mypy ./src --verbose
